openapi: 3.0.0
info:
  title: Nexmo Conversion API
  version: 1.0.2
  description: >-
    The Conversion API allows you to tell Nexmo about the reliability of your
    2FA communications. Sending conversion data back to us means that Nexmo can
    deliver messages faster and more reliably.

    The conversion data you send us is confidential: Nexmo does not share it
    with third parties.

    In order to identify the carriers who provide the best performance, Nexmo
    continually tests the routes we use to deliver SMS and voice calls. Using
    Adaptive Routing™, Nexmo actively reroutes messages through different
    carrier routes and ensures faster and more reliable delivery for your
    messages. The route choice is made using millions of real-time conversion
    data points.
  contact:
    name: Nexmo.com
    email: devrel@nexmo.com
    url: "https://developer.nexmo.com/"
    x-twitter: Nexmo
  termsOfService: "https://www.nexmo.com/terms-of-use"
  license:
    name: The MIT License (MIT)
    url: "https://opensource.org/licenses/MIT"
  x-logo:
    url: "https://twitter.com/Nexmo/profile_image?size=original"
  x-apiClientRegistration: "https://dashboard.nexmo.com/sign-up"
servers:
  - url: "https://api.nexmo.com/conversions"
externalDocs:
  url: "https://developer.nexmo.com/api/conversion"
  x-sha1: 8ad8bc6b0c51af4ca458c13cfced6124783ab113
security:
  - apiKey: []
    apiSecret: []
  - apiKey: []
    apiSig: []
tags:
  - name: SMS Conversion
    description: SMS Conversion Request
  - name: Voice Conversion
    description: Voice Conversion Request
paths:
  /sms:
    post:
      operationId: smsConversion
      summary: Tell Nexmo if your SMS message was successful
      description: >-
        Send a Conversion API request with information about the SMS message
        identified by `message-id`. Nexmo uses your conversion data and internal
        information about `message-id` to help improve our routing of messages
        in the future.
      tags:
        - SMS Conversion
      parameters:
        - $ref: "#/components/parameters/message-id"
        - $ref: "#/components/parameters/delivered"

      responses:
        "200":
          description: OK

          content:
              text/plain:
                schema:
                  type: string
                example: OK

        "401":
          description: >-
            Account permission is not setup to access API.

          content:
           text/plain:
            schema:
              type: string
            example:
                "401 Permission denied"

        "402":
          description:  >-
            - Wrong or expired JWT Tokens

            - Request from an account is blocked

            - Wrong credentials(api_key or api_secret)

            - Conversions API call not enabled on account.

          content:
            text/plain:
              schema:
                type: string
              example:
                  402 Bad account credentials

        "421":
          description:  >-
            Mandatory field "message-id" is unavailable in request body

          content:
            text/plain:
              schema:
                type: string
              example:
                  421 Missing message-id param

        "422":
          description:  >-
            - Mandatory field 'delivered' is unavailable in request body"

            - Field 'delivered' is other than 0|1|true|false
          content:
            text/plain:
              schema:
                type: string
              example:
                  "422 Missing or Invalid 'delivered' param"

        "426":
          description:  >-
            - Mandatory field 'messageId' length is lesser than 16 or greater than 50
          content:
            text/plain:
              schema:
                type: string
              example:
                  "426 Invalid 'messageId' param"

      requestBody:
          $ref: "#/components/requestBodies/Ok"
  /voice:
    post:
      operationId: voiceConversion
      summary: Tell Nexmo if your voice call was successful
      description: >-
        Send a Conversion API request with information about the Call or
        Text-To-Speech identified by `message-id`. Nexmo uses your conversion
        data and internal information about `message-id` to help improve our
        routing of messages in the future.
      tags:
        - Voice Conversion
      parameters:
        - $ref: "#/components/parameters/message-id"
        - $ref: "#/components/parameters/delivered"

      responses:

        "200":
          description: OK

          content:
              text/plain:
                schema:
                  type: string
                example: OK

        "401":
          description: >-
            Account permission is not setup to access API.

          content:
           text/plain:
            schema:
              type: string
            example:
                "401 Permission denied"

        "402":
          description:  >-
            - Wrong or expired JWT Tokens

            - Request from an account is blocked

            - Wrong credentials(api_key or api_secret)

            - Conversions API call not enabled on account.

          content:
            text/plain:
              schema:
                type: string
              example:
                  402 Bad account credentials

        "421":
          description:  >-
            Mandatory field "message-id" is unavailable in request body

          content:
            text/plain:
              schema:
                type: string
              example:
                  421 Missing message-id param

        "422":
          description:  >-
            - Mandatory field 'delivered' is unavailable in request body"

            - Field 'delivered' is other than 0|1|true|false
          content:
            text/plain:
              schema:
                type: string
              example:
                  "422 Missing or Invalid 'delivered' param"

        "426":
          description:  >-
            - Mandatory field 'messageId' length is lesser than 16 or greater than 50
          content:
            text/plain:
              schema:
                type: string
              example:
                  "426 Invalid 'messageId' param"

      requestBody:
          $ref: "#/components/requestBodies/Ok"
components:
  schemas:
    message-id:
      type: string
      example: 0A000000010CA46C
      description: >-
        The ID you receive in the response to a request. * From the Verify API -
        use the `event_id` in the response to Verify Check. * From the SMS API -
        use the `message-id` * From the Text-To-Speech API - use the `call-id` *
        From the Text-To-Speech-Prompt API - use the `call-id`

    delivered:
      type: string
      example: true
      description: >-
        Set to _true_ if your user replied to the message you sent. Otherwise,
        set to _false_.

        **Note**: for curl, use 0 and 1.
      enum:
        - true
        - false
        - 0
        - 1
  securitySchemes:
    apiKey:
      type: apiKey
      name: api_key
      in: query
      description: >-
        You can find your API key in your [account
        overview](https://dashboard.nexmo.com/account-overview)
    apiSecret:
      type: apiKey
      name: api_secret
      in: query
      description: >-
        You can find your API secret in your [account
        overview](https://dashboard.nexmo.com/account-overview)
    apiSig:
      type: apiKey
      name: sig
      in: query
      description: >-
        The hash of the request parameters in alphabetical order, a timestamp
        and the signature secret. For example: `sig=SIGNATURE`

  requestBodies:
      Ok:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                api_key:
                  $ref: "#/components/securitySchemes/apiKey"
                api_secret:
                  $ref: "#/components/securitySchemes/apiSecret"
                message-id:
                  $ref: "#/components/parameters/message-id"
                delivered:
                  $ref: "#/components/parameters/delivered"
